### ISSUE TITLE
Question about mdx 2.0

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [ikey4u/wikit#3]
Hi,

I noticed the README mentioned the original mdx structure described by [Xiaoqiang Wang](https://bitbucket.org/xwang/mdict-analysis/src/master/) and something called mdx 2.0. Is Xiaoqiang Wang's description considered 1.0? What's the difference between them? I'm a little confused as mdx is a pretty old file type and the original author started using a newer version in his mdict program several years ago. But the file structure of that version hasn't been reverse-engineered. Is mdx 2.- refer to this newer file format?

Thanks.

**Comment by ikey4u** [comment]
@0x7FFFFFFFFFFFFFFF the most common mdx format version are 2.0 and below, you may think the post made by wang is about these versions(most part of the structure between different version are the same but with a few difference). Most of the dictionary resource is made by the tool supplied here https://github.com/zhansliu/writemdict. But this tool seems not maintained at all and there are some improvements in docs and code.

For any other mdx version(above 2.0), it is still closed source and i  think it is not a good idea to do reverse engineer to recover the new format, since there are enough mdx resouces which are made by the open sourced  writemdict tool. Besides, is there any good reason to keep up with the new mdx format? i think no.
